# Generated by Django 3.0.1 on 2020-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('ventilators', models.IntegerField(default=100)),
                ('beds', models.IntegerField(default=200)),
                ('hospitals', models.CharField(max_length=50)),
                ('main_doctors', models.CharField(max_length=50)),
            ],
        ),
    ]
