# Generated by Django 3.0.1 on 2020-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200525_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='beds',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='ventilator',
            old_name='ventilators',
            new_name='available',
        ),
        migrations.AddField(
            model_name='bed',
            name='available',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='ventilator',
            name='total',
            field=models.IntegerField(default=100),
        ),
    ]
