# Generated by Django 3.0.1 on 2020-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200525_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=200)),
                ('recovered', models.IntegerField(default=20)),
                ('positive', models.IntegerField(default=100)),
            ],
        ),
    ]
