# Generated by Django 3.0.1 on 2020-05-26 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_patient_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hospital',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ventilator',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
