# Generated by Django 3.0.1 on 2020-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200526_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total',
        ),
        migrations.AddField(
            model_name='hospital',
            name='nodoctor',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nonurse',
            field=models.IntegerField(default=30),
        ),
    ]
