# Generated by Django 3.0.1 on 2020-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200526_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='ventilator',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
