# Generated by Django 3.0.1 on 2020-05-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200526_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='positive',
            field=models.IntegerField(default=180),
        ),
    ]
