# Generated by Django 3.0.1 on 2020-05-26 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_patient_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
